"""drop columns

Revision ID: 0134670fc6af
Revises: 4683caa3af5c
Create Date: 2021-05-03 10:47:45.819383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0134670fc6af'
down_revision = '4683caa3af5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fightsDB') as batch_op:
        batch_op.drop_column('fight_status')
        batch_op.drop_column('ntest')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fightsDB', sa.Column('ntest', sa.VARCHAR(), nullable=True))
    op.add_column('fightsDB', sa.Column('fight_status', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
