"""test migrate

Revision ID: 4683caa3af5c
Revises: 
Create Date: 2021-05-03 10:45:48.172801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4683caa3af5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fightsDB', sa.Column('ntest', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fightsDB', 'ntest')
    # ### end Alembic commands ###
