"""empty message

Revision ID: aeffdb8d5938
Revises: d0aa75e2e31f
Create Date: 2021-04-25 19:24:40.350937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeffdb8d5938'
down_revision = 'd0aa75e2e31f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fightsDB', sa.Column('fight_result', sa.String(), nullable=True))
    op.drop_column('fightsDB', 'fight_rusult')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fightsDB', sa.Column('fight_rusult', sa.VARCHAR(), nullable=True))
    op.drop_column('fightsDB', 'fight_result')
    # ### end Alembic commands ###
