"""finish_round_id column added

Revision ID: f02554800d0a
Revises: 5b8a2d71451c
Create Date: 2021-05-05 13:06:04.172166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f02554800d0a'
down_revision = '5b8a2d71451c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrationDB', sa.Column('finish_round_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'registrationDB', 'roundsDB', ['finish_round_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registrationDB', type_='foreignkey')
    op.drop_column('registrationDB', 'finish_round_id')
    # ### end Alembic commands ###
