"""rounds test field table

Revision ID: f3d406349071
Revises: d370e1daba4d
Create Date: 2021-04-23 11:54:34.601727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d406349071'
down_revision = 'd370e1daba4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roundsDB', 'test_field')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roundsDB', sa.Column('test_field', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
